-- require("configs.global")
require("configs.options")
require("configs.colorizer")
require("configs.bufferline")
-- require("configs.feline")
-- require("configs.lualine")
-- require("configs.barbar")
require("configs.galaxy-statusline")
-- require("configs.indentguides")
require("configs.ibl")
require("configs.treesitter")
require("configs.mytelescope")
-- require("configs.indent-blankline")
-- require("configs.peekup")
-- require("ibl").setup()
-- require('configs.scribe-config')
-- require('configs.hop-config')

-- require("configs.shader")
-- require("configs.scroll")
-- require("configs.css-colors")
-- require("configs.hop-config")
-- ############## Themes ##########
-- require("configs.theme")
-- require('configs.rose-pine')
-- require('configs.catpuccin')
require('configs.tokyonight')
-- require('configs.gruvbox')
-- require('configs.nightfox')
-- require('configs.kanagawa')
-- require('configs.nordic')
-- require('configs.nord-config')
-- require('configs.onenord')
-- ############### minimal ################
-- require('configs.noir-buddy')
-- require("configs.nui")
-- require('configs.polish')
require("configs.notify")
require("configs.sniprun")
require('configs.reset-tele')
require("configs.telescope-coc")
require('configs.alpha')
require('configs.harpoon')
require("configs.undotree")

-- require("configs.lsp-config")
-- require("configs.nvimcmp")
-- require("configs.fidget")
-- require("configs.newlua-snips")
-- require("configs.snips.java")
-- require("configs.coq-comp")
-- require("configs.lspnotify")
-- require('configs.tabscope')
-- require('configs.zenmode')
-- require('configs.oil')
-- require("configs.cyberdream")
-- require('configs.mellow')
-- require("configs.zenmode")
-- require("configs.cinnamon-smooth")
require("configs.transparent")
require("configs.examples.plenary-demo")
require("fzf-lua")
require("configs.hlargs")
-- require("configs.markid")
-- require("configs.codeium")
require("configs.dbee")
